[workspace]
members = [
    "cashweb",
    "cashweb-auth-wrapper",
    "cashweb-bitcoin",
    "cashweb-bitcoin-client",
    "cashweb-bot",
    "cashweb-payments",
    "cashweb-relay",
    "cashweb-token"
]
